### ISSUE TITLE
Compilation fails under stack with missing fl_types.h

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#45] opened 2017-02-14 15:00 UTC
Using the steps posted in the Windows install, the final step to build the hello world program using stack fails:

Building fltkhs-0.5.0.7...
Preprocessing library fltkhs-0.5.0.7...
In file included from .stack-work\dist\2fae85dd\build\Graphics\UI\FLTK\LowLevel\Ask.chs.h:3:0:
./c-src/Fl_Types.h:3:25: fatal error: FL/fl_types.h: No such file or directory
compilation terminated.
c2hs.exe: Error during preprocessing custom header file

**Comment by deech** [comment] 2017-02-14 15:17
Does `/usr/include/FL/fl_types.h` or `/usr/local/include/FL/fl_types.h` or `<fltk-install-prefix>/FL/fl_types.h` exist?

**Comment by jputcu** [comment] 2017-02-14 15:26
Yes, fl_types.h can be found in /mingw32/include, the include path given by fltk-config:

$ fltk-config --cflags
-I/mingw32/include -I/mingw32/include/FL/images -mwindows -DWIN32 -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

I'm running Windows 7

**Comment by jputcu** [comment] 2017-02-14 15:41
Ok, explicitly setting ` export CPATH=/mingw32/include` and running `stack install` again gets me passed this error.
Now it is complaining it can't find certain 64-bit Haskell Platform directories while I'm running a x86 variant.
(Perhaps best to make that another issue)

**Comment by deech** [comment] 2017-02-14 17:54
Oh interesting. I didn't test the install Haskell Platform, I just used the Stack Windows installer. Let me see if I can get any further.

**Comment by deech** [comment] 2017-02-14 23:45
I just installed the latest [Haskell Platform](https://www.haskell.org/platform/windows.html) for 64 bit Windows and followed the Windows install instructions from scratch and was not able to reproduce your error. I am running 64 bit Windows 8. I'll test on Windows 7 when I can get my hands on a machine.

FWIW here's what `fltk-config --cflags` gave me:
```
-I/mingw64/include -I/mingw64/include/FL/images -mwindows -DWIN32 -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
```

There's no mention of the `mingw32` directory. Are you running 32-bit?

**Comment by jputcu** [comment] 2017-02-15 08:05
Yes, for supporting older hardware I'm using the 32-bit Haskell Platform.

**Comment by jputcu** [comment] 2017-02-15 09:08
Tried again using latest Haskell Platform 8.0.2 32-bit.
Changed the hello world yaml to use lts-8.0 and then `stack install -v --system-ghc`.
Everything stack builds is located in a `i386-windows`.
In the end it fails with:
~~~~
 Building fltkhs-0.5.0.7...
    Preprocessing library fltkhs-0.5.0.7...
    C:\Users\jorisp\AppData\Local\Temp\stack6680\fltkhs-0.5.0.7\In file included from .stack-work\dist\5f9bc736\build\Graphics\UI\FLTK\LowLevel\Ask.chs.h:3:0:
    C:\Users\jorisp\AppData\Local\Temp\stack6680\fltkhs-0.5.0.7\c-src\Fl_Types.h:3:25: fatal error: FL/fl_types.h: No such file or directory
    compilation terminated.
    c2hs.exe: Error during preprocessing custom header file
~~~~~

**Comment by jputcu** [comment] 2017-02-15 09:30
I see some hard coded 64-bit paths in fltkhs' `Setup.hs`.

**Comment by deech** [comment] 2017-02-15 12:40
Yes, I had to do some unfortunate path munging and didn't have access to a 32 bit machine. In any case I pushed a fix to `master`. Do you mind pulling and trying? Thanks for your patience.

**Comment by jputcu** [comment] 2017-02-15 13:12
Tried building and succeeded, thanks.

**Comment by deech** [comment] 2017-02-15 13:15
Great, thanks! I'll release another version and update the various demos etc. later today.

**Closed** 2017-02-17 08:24 UTC
